# ConfigureTreeSitter.cmake
# 配置 Tree-sitter 语法高亮支持
#
# 此文件包含查找和配置 Tree-sitter 的逻辑
# 如果 Tree-sitter 未找到，将使用原生语法高亮器
#
# 使用方式:
#   include(ConfigureTreeSitter)
#
# 定义变量:
#   BUILD_TREE_SITTER_SUPPORT - 如果启用 Tree-sitter 支持则为 TRUE
#   TREE_SITTER_LIBRARIES     - Tree-sitter 库文件
#   TREE_SITTER_INCLUDE_DIRS  - Tree-sitter 包含目录
#   TREE_SITTER_*_LIB         - 各个语言库变量（映射后的）

# 查找 Tree-sitter（语法高亮）
find_package(TreeSitter QUIET)
if(TreeSitter_FOUND)
    set(BUILD_TREE_SITTER_SUPPORT ON)
    set(TREE_SITTER_LIBRARIES ${TreeSitter_LIBRARIES})
    set(TREE_SITTER_INCLUDE_DIRS ${TreeSitter_INCLUDE_DIRS})
    message(STATUS "✓ Tree-sitter found - syntax highlighting enabled")
    message(STATUS "  Libraries: ${TREE_SITTER_LIBRARIES}")
    message(STATUS "  Include dirs: ${TREE_SITTER_INCLUDE_DIRS}")
    if(TreeSitter_VERSION)
        message(STATUS "  Version: ${TreeSitter_VERSION}")
    endif()

    # 查找 Tree-sitter 语言库（可选，但推荐）
    include(FindTreeSitterLanguages)

    # 映射语言库变量名（保持兼容性）
    if(TreeSitter_CPP_FOUND)
        set(TREE_SITTER_CPP_LIB ${TreeSitter_CPP_LIBRARY})
    endif()
    if(TreeSitter_C_FOUND)
        set(TREE_SITTER_C_LIB ${TreeSitter_C_LIBRARY})
    endif()
    if(TreeSitter_PYTHON_FOUND)
        set(TREE_SITTER_PYTHON_LIB ${TreeSitter_PYTHON_LIBRARY})
    endif()
    if(TreeSitter_JAVASCRIPT_FOUND)
        set(TREE_SITTER_JAVASCRIPT_LIB ${TreeSitter_JAVASCRIPT_LIBRARY})
    endif()
    if(TreeSitter_TYPESCRIPT_FOUND)
        set(TREE_SITTER_TYPESCRIPT_LIB ${TreeSitter_TYPESCRIPT_LIBRARY})
    endif()
    if(TreeSitter_JSON_FOUND)
        set(TREE_SITTER_JSON_LIB ${TreeSitter_JSON_LIBRARY})
    endif()
    if(TreeSitter_MARKDOWN_FOUND)
        set(TREE_SITTER_MARKDOWN_LIB ${TreeSitter_MARKDOWN_LIBRARY})
    endif()
    if(TreeSitter_BASH_FOUND)
        set(TREE_SITTER_BASH_LIB ${TreeSitter_BASH_LIBRARY})
    endif()
    if(TreeSitter_RUST_FOUND)
        set(TREE_SITTER_RUST_LIB ${TreeSitter_RUST_LIBRARY})
    endif()
    if(TreeSitter_GO_FOUND)
        set(TREE_SITTER_GO_LIB ${TreeSitter_GO_LIBRARY})
    endif()
    if(TreeSitter_JAVA_FOUND)
        set(TREE_SITTER_JAVA_LIB ${TreeSitter_JAVA_LIBRARY})
    endif()
    if(TreeSitter_CMAKE_FOUND)
        set(TREE_SITTER_CMAKE_LIB ${TreeSitter_CMAKE_LIBRARY})
    endif()
    if(TreeSitter_TCL_FOUND)
        set(TREE_SITTER_TCL_LIB ${TreeSitter_TCL_LIBRARY})
    endif()
    if(TreeSitter_FORTRAN_FOUND)
        set(TREE_SITTER_FORTRAN_LIB ${TreeSitter_FORTRAN_LIBRARY})
    endif()
    if(TreeSitter_HASKELL_FOUND)
        set(TREE_SITTER_HASKELL_LIB ${TreeSitter_HASKELL_LIBRARY})
    endif()
    if(TreeSitter_LUA_FOUND)
        set(TREE_SITTER_LUA_LIB ${TreeSitter_LUA_LIBRARY})
    endif()
    if(TreeSitter_YAML_FOUND)
        set(TREE_SITTER_YAML_LIB ${TreeSitter_YAML_LIBRARY})
    endif()
    if(TreeSitter_XML_FOUND)
        set(TREE_SITTER_XML_LIB ${TreeSitter_XML_LIBRARY})
    endif()
    if(TreeSitter_CSS_FOUND)
        set(TREE_SITTER_CSS_LIB ${TreeSitter_CSS_LIBRARY})
    endif()
    if(TreeSitter_SQL_FOUND)
        set(TREE_SITTER_SQL_LIB ${TreeSitter_SQL_LIBRARY})
    endif()
    if(TreeSitter_RUBY_FOUND)
        set(TREE_SITTER_RUBY_LIB ${TreeSitter_RUBY_LIBRARY})
    endif()
    if(TreeSitter_PHP_FOUND)
        set(TREE_SITTER_PHP_LIB ${TreeSitter_PHP_LIBRARY})
    endif()
    if(TreeSitter_SWIFT_FOUND)
        set(TREE_SITTER_SWIFT_LIB ${TreeSitter_SWIFT_LIBRARY})
    endif()
    if(TreeSitter_KOTLIN_FOUND)
        set(TREE_SITTER_KOTLIN_LIB ${TreeSitter_KOTLIN_LIBRARY})
    endif()
    if(TreeSitter_SCALA_FOUND)
        set(TREE_SITTER_SCALA_LIB ${TreeSitter_SCALA_LIBRARY})
    endif()
    if(TreeSitter_R_FOUND)
        set(TREE_SITTER_R_LIB ${TreeSitter_R_LIBRARY})
    endif()
    if(TreeSitter_PERL_FOUND)
        set(TREE_SITTER_PERL_LIB ${TreeSitter_PERL_LIBRARY})
    endif()
    if(TreeSitter_DOCKERFILE_FOUND)
        set(TREE_SITTER_DOCKERFILE_LIB ${TreeSitter_DOCKERFILE_LIBRARY})
    endif()
    if(TreeSitter_MAKEFILE_FOUND)
        set(TREE_SITTER_MAKEFILE_LIB ${TreeSitter_MAKEFILE_LIBRARY})
    endif()
    if(TreeSitter_VIM_FOUND)
        set(TREE_SITTER_VIM_LIB ${TreeSitter_VIM_LIBRARY})
    endif()
    if(TreeSitter_POWERSHELL_FOUND)
        set(TREE_SITTER_POWERSHELL_LIB ${TreeSitter_POWERSHELL_LIBRARY})
    endif()

    # 新增优化语言支持
    if(TreeSitter_MESON_FOUND)
        set(TREE_SITTER_MESON_LIB ${TreeSitter_MESON_LIBRARY})
    endif()
    if(TreeSitter_TOML_FOUND)
        set(TREE_SITTER_TOML_LIB ${TreeSitter_TOML_LIBRARY})
    endif()
    if(TreeSitter_NIM_FOUND)
        set(TREE_SITTER_NIM_LIB ${TreeSitter_NIM_LIBRARY})
    endif()
    # 函数式/编译器相关语言支持映射
    if(TreeSitter_LISP_FOUND)
        set(TREE_SITTER_LISP_LIB ${TreeSitter_LISP_LIBRARY})
    endif()
    if(TreeSitter_SML_FOUND)
        set(TREE_SITTER_SML_LIB ${TreeSitter_SML_LIBRARY})
    endif()
    if(TreeSitter_LLVM_FOUND)
        set(TREE_SITTER_LLVM_LIB ${TreeSitter_LLVM_LIBRARY})
    endif()
    if(TreeSitter_RISCV_FOUND)
        set(TREE_SITTER_RISCV_LIB ${TreeSitter_RISCV_LIBRARY})
    endif()
else()
    set(BUILD_TREE_SITTER_SUPPORT OFF)
    message(WARNING "✗ Tree-sitter not found, will use native syntax highlighter")
    message(STATUS "  Install with: sudo apt install libtree-sitter-dev")
    message(STATUS "  Or build from source: https://github.com/tree-sitter/tree-sitter")
endif()
